# Generated by Django 5.2.3 on 2025-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llavetorneo',
            name='partido_jugado',
        ),
        migrations.AddField(
            model_name='llavetorneo',
            name='estado_partido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('jugado', 'Jugado')], default='pendiente', max_length=20),
        ),
    ]
