# Generated by Django 5.2.3 on 2025-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='sets_jugador_1',
            new_name='set1_jugador1',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='sets_jugador_2',
            new_name='set3_jugador2',
        ),
        migrations.AddField(
            model_name='resultado',
            name='set1_jugador2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set2_jugador1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set2_jugador2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set3_jugador1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set4_jugador1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set4_jugador2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set5_jugador1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set5_jugador2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='sets_ganados_jugador1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='sets_ganados_jugador2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
