# Generated by Django 5.2.3 on 2025-06-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0002_rename_sets_jugador_1_resultado_set1_jugador1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='set6_jugador1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set6_jugador2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set7_jugador1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set7_jugador2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set8_jugador1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set8_jugador2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set9_jugador1',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='set9_jugador2',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
