# Generated by Django 5.2.3 on 2025-06-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0003_resultado_set6_jugador1_resultado_set6_jugador2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llavetorneo',
            name='tipo_llave',
            field=models.CharField(choices=[('normal', 'Normal'), ('tercer_lugar', 'Tercer Lugar')], default='normal', max_length=20),
        ),
    ]
