# Generated by Django 5.2.1 on 2025-06-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0003_remove_jugador_organizador_alter_jugador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='rut',
            field=models.CharField(default=12345669, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
