# Generated by Django 5.2.1 on 2025-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0004_jugador_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
