# Generated by Django 5.2.3 on 2025-06-29 05:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0004_llavetorneo_tipo_llave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'verbose_name': 'Usuario Personalizado', 'verbose_name_plural': 'Usuarios Personalizados'},
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='username',
            field=models.CharField(max_length=20, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='usuariopersonalizado',
            unique_together={('email', 'tipo_usuario')},
        ),
    ]
