# Generated by Django 5.2.1 on 2025-06-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0005_jugador_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='categoria',
        ),
    ]
