# Generated by Django 5.2.1 on 2025-06-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0006_remove_jugador_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='edad_maxima',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='edad_minima',
        ),
        migrations.AddField(
            model_name='categoria',
            name='anio_maximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='anio_minimo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
