# Generated by Django 5.2.1 on 2025-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0007_remove_categoria_edad_maxima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='anio_maximo',
            new_name='edad_maxima',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='anio_minimo',
            new_name='edad_minima',
        ),
    ]
