# Generated by Django 5.2.3 on 2025-06-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0007_partido_arbitro_partido_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='partido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_detallado', to='gestiontorneo.partido'),
        ),
    ]
