# Generated by Django 5.2.1 on 2025-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0008_rename_anio_maximo_categoria_edad_maxima_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='club',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='club',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='club',
            name='organizador',
        ),
    ]
