# Generated by Django 5.2.3 on 2025-06-29 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0009_torneo_finalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitroTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_asignados', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitros_asignados', to='gestiontorneo.torneo')),
            ],
            options={
                'verbose_name': 'Árbitro del Torneo',
                'verbose_name_plural': 'Árbitros del Torneo',
                'unique_together': {('torneo', 'arbitro')},
            },
        ),
    ]
