# Generated by Django 5.2.1 on 2025-06-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0009_alter_club_unique_together_alter_club_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='federado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
