# Generated by Django 5.2.3 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0010_arbitrotorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='pendiente_confirmacion',
            field=models.BooleanField(default=False),
        ),
    ]
