# Generated by Django 5.2.1 on 2025-06-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0010_torneo_federado_torneo_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiontorneo.categoria'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='todo_competidor',
            field=models.BooleanField(default=False),
        ),
    ]
