# Generated by Django 5.2.3 on 2025-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0011_torneo_pendiente_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='pendiente_confirmacion',
            field=models.BooleanField(default=False),
        ),
    ]
