# Generated by Django 5.2.3 on 2025-06-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0011_torneo_categoria_torneo_todo_competidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='inscripciones_cerradas',
            field=models.BooleanField(default=False),
        ),
    ]
