# Generated by Django 5.2.3 on 2025-06-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0012_partido_pendiente_confirmacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='pendiente_confirmacion',
        ),
    ]
