# Generated by Django 5.2.3 on 2025-06-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0012_torneo_inscripciones_cerradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('', 'Sin definir'), ('llaves', 'Llaves (Brackets)'), ('grupos', 'Fases de Grupos')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='torneo',
            name='torneo_iniciado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GrupoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='gestiontorneo.torneo')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('torneo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ParticipanteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_cabeza_serie', models.BooleanField(default=False)),
                ('posicion_grupo', models.PositiveIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='gestiontorneo.grupotorneo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontorneo.jugador')),
            ],
            options={
                'ordering': ['posicion_grupo'],
                'unique_together': {('grupo', 'jugador')},
            },
        ),
    ]
