# Generated by Django 5.2.3 on 2025-06-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0013_torneo_modalidad_torneo_torneo_iniciado_grupotorneo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveIntegerField()),
                ('posicion', models.PositiveIntegerField()),
                ('partido_jugado', models.BooleanField(default=False)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaves_ganadas', to='gestiontorneo.jugador')),
                ('jugador1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaves_jugador1', to='gestiontorneo.jugador')),
                ('jugador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaves_jugador2', to='gestiontorneo.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llaves', to='gestiontorneo.torneo')),
            ],
            options={
                'ordering': ['ronda', 'posicion'],
                'unique_together': {('torneo', 'ronda', 'posicion')},
            },
        ),
    ]
