# Generated by Django 5.2.3 on 2025-06-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0013_remove_torneo_pendiente_confirmacion'),
    ]

    operations = [
    ]
