# Generated by Django 5.2.3 on 2025-06-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontorneo', '0014_llavetorneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorBYE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='BYE', max_length=50)),
                ('posicion_bye', models.PositiveIntegerField()),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byes', to='gestiontorneo.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'posicion_bye')},
            },
        ),
        migrations.AddField(
            model_name='llavetorneo',
            name='bye1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaves_bye1', to='gestiontorneo.jugadorbye'),
        ),
        migrations.AddField(
            model_name='llavetorneo',
            name='bye2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaves_bye2', to='gestiontorneo.jugadorbye'),
        ),
    ]
